### ISSUE TITLE
Fatal error on ProductView plugin in case of $product not available

### ISSUE THREAD

**Issue by pawel989** [GetResponse/magento2-module#2]
The plugin CustomerData/TrackingCode/ProductView.php throws a fatal error in the afterToHtml method, in case of $product not being available on the subject. 

Addition of a simple product availability check like this would help a lot!
`
 public function afterToHtml(Subject $subject, string $html): string
  {
      $product = $subject->getProduct();
      if (!$product) {
          return $html;
      }
      ...
   }
`

**Comment by woojos** [comment]
Thanks Paweł, we will take care of that.

**Comment by rkarkut** [comment]
Hi Paweł, issue already fixed in our latest plugin version.
